In [ ]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [ ]:
df = pd.read_excel('3Y_Data_SP500.xlsx')
df.head()

   Unnamed: 0                 Date      Open      High       Low     Close
0         251  2019-02-01 00:00:00  2,476.96  2,519.49  2,467.47  2,510.03
1         250  2019-03-01 00:00:00  2,491.92  2,493.14  2,443.96  2,447.89
2         249  2019-04-01 00:00:00  2,474.33  2,538.07  2,474.33  2,531.94
3         248  2019-07-01 00:00:00  2,535.61  2,566.16  2,524.56  2,549.69
4         247  2019-08-01 00:00:00  2,568.11  2,579.82  2,547.56  2,574.41

In [ ]:
df.dtypes

Unnamed: 0     int64
Date          object
Open          object
High          object
Low           object
Close         object
dtype: object

In [ ]:
df["Open"] = [float(str(i).replace(",", "")) for i in df["Open"]]

In [ ]:
df["High"] = [float(str(i).replace(",", "")) for i in df["High"]]

In [ ]:
df["Low"] = [float(str(i).replace(",", "")) for i in df["Low"]]

In [ ]:
df["Close"] = [float(str(i).replace(",", "")) for i in df["Close"]]

In [ ]:
df['Date'] = df["Date"].astype('datetime64[ns]')

In [ ]:
df['diffHigh']=df['High']-df['Open']

In [ ]:
df['difflow']=df['Open']-df['Low']

In [ ]:
df['diffClose']=df['Close']-df['Open']

In [ ]:
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30

In [ ]:
df['Average'] = (df['diffHigh'] + df['difflow']+df['diffClose'])/3
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose,Average,Target_price,Gain_lost,Gain_lost1,Target_price1,Target_price2,Gain_lost2
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07,28.363333,2496.421248,Gain,Gain,2496.421248,2457.498752,Lost
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03,1.716667,2511.381248,Lost,Lost,2511.381248,2472.458752,Gain
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61,40.450000,2493.791248,Gain,Gain,2493.791248,2454.868752,Lost
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08,18.560000,2555.071248,Gain,Gain,2555.071248,2516.148752,Lost
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30,12.853333,2587.571248,Lost,Lost,2587.571248,2548.648752,Gain

In [ ]:
df['Average'].mean()

13.42639806252752

In [ ]:
df['diffHigh'].mean()

19.052206076618234

In [ ]:
df['Target_price1']=df['Open']+13.43

In [ ]:
df['Target_price2']=df['Open']-13.43

In [ ]:
df=df.drop(columns=['Target_price','Gain_lost','Target_price2'])

In [ ]:
df=df.drop(columns=['Gain_lost1','Target_price1','Gain_lost2'])

In [ ]:
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose,Average,Target_price1,Target_price2
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07,28.363333,2490.39,2463.53
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03,1.716667,2505.35,2478.49
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61,40.450000,2487.76,2460.90
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08,18.560000,2549.04,2522.18
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30,12.853333,2581.54,2554.68

In [ ]:
df['Gain_lost1'] = np.select([df['Target_price1']<df['High'],df['Target_price1']>df['High']], ['Gain','Lost'])
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose,Average,Target_price1,Target_price2,Gain_lost1
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07,28.363333,2490.39,2463.53,Gain
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03,1.716667,2505.35,2478.49,Lost
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61,40.450000,2487.76,2460.90,Gain
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08,18.560000,2549.04,2522.18,Gain
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30,12.853333,2581.54,2554.68,Lost

In [ ]:
df['Gain_lost2'] = np.select([df['Target_price2']<df['Low'],df['Target_price2']>df['Low']], ['Lost','Gain'])
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose,Average,Target_price1,Target_price2,Gain_lost1,Gain_lost2
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07,28.363333,2490.39,2463.53,Gain,Lost
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03,1.716667,2505.35,2478.49,Lost,Gain
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61,40.450000,2487.76,2460.90,Gain,Lost
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08,18.560000,2549.04,2522.18,Gain,Lost
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30,12.853333,2581.54,2554.68,Lost,Gain

In [ ]:
df["Gain_lost1"].value_counts()

Lost    387
Gain    370
Name: Gain_lost1, dtype: int64

In [ ]:
df["Gain_lost2"].value_counts()

Lost    405
Gain    351
0         1
Name: Gain_lost2, dtype: int64

Accuracy= 49%
BASED ON THIS WORK THE ACCURACY OF OUR ALGORITHM IS 49% WHICH IS CALCULATED BY DIVIDING THE NUMBER OF Gain BY THE TOTAL NUMBER OF OBSERVATIONS 503 THEN MULTIPLY BY 100

In [ ]:
#for selling it's 46.4%

**Validation using data from 2022**

In [ ]:
df2=pd.read_csv('SP_2022.csv')

In [ ]:
df2.dtypes

Date     object
Open     object
High     object
Low      object
Close    object
dtype: object

In [ ]:
df2["Open"] = [float(str(i).replace(",", "")) for i in df2["Open"]]

In [ ]:
df2["High"] = [float(str(i).replace(",", "")) for i in df2["High"]]

In [ ]:
df2["Low"] = [float(str(i).replace(",", "")) for i in df2["Low"]]

In [ ]:
df2["Close"] = [float(str(i).replace(",", "")) for i in df2["Close"]]

In [ ]:
df2['Date'] = df2["Date"].astype('datetime64[ns]')

In [ ]:
df2['Target_price1']=df2['Open']+13.43

In [ ]:
df2['Gain_lost1'] = np.select([df2['Target_price1']<df2['High'],df2['Target_price1']>df2['High']], ['Gain','Lost'])
df2.head()

        Date     Open     High      Low    Close  Target_price1 Gain_lost1
0 2022-12-30  3828.85  3839.85  3800.34  3839.50        3842.28       Lost
1 2022-12-29  3805.45  3858.19  3805.45  3849.28        3818.88       Gain
2 2022-12-28  3829.56  3848.32  3780.78  3783.22        3842.99       Gain
3 2022-12-27  3843.34  3846.65  3813.22  3829.25        3856.77       Lost
4 2022-12-23  3813.11  3845.80  3797.01  3844.82        3826.54       Gain

In [ ]:
df2["Gain_lost1"].value_counts()

Gain    186
Lost     65
Name: Gain_lost1, dtype: int64

In [ ]:
#75% Accuracy