In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [2]:
df = pd.read_excel('3Y_Data_SP500.xlsx')
df.head()

   Unnamed: 0                 Date      Open      High       Low     Close
0         251  2019-02-01 00:00:00  2,476.96  2,519.49  2,467.47  2,510.03
1         250  2019-03-01 00:00:00  2,491.92  2,493.14  2,443.96  2,447.89
2         249  2019-04-01 00:00:00  2,474.33  2,538.07  2,474.33  2,531.94
3         248  2019-07-01 00:00:00  2,535.61  2,566.16  2,524.56  2,549.69
4         247  2019-08-01 00:00:00  2,568.11  2,579.82  2,547.56  2,574.41

In [3]:
df["Open"] = [float(str(i).replace(",", "")) for i in df["Open"]]

In [4]:
df["High"] = [float(str(i).replace(",", "")) for i in df["High"]]

In [5]:
df["Low"] = [float(str(i).replace(",", "")) for i in df["Low"]]

In [6]:
df["Close"] = [float(str(i).replace(",", "")) for i in df["Close"]]

In [7]:
df['Date'] = df["Date"].astype('datetime64[ns]')

In [8]:
df['diffHigh']=df['High']-df['Open']
df['difflow']=df['Open']-df['Low']
df['diffClose']=df['Close']-df['Open']

In [9]:
df['Average'] = (df['diffHigh'] + df['difflow']+df['diffClose'])/3
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose,Average
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07,28.363333
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03,1.716667
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61,40.450000
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08,18.560000
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30,12.853333

In [10]:
df['Average'].median()

9.443333333333308

In [12]:
df['Target_price1']=df['Open']+9.44

In [13]:
df['Target_price2']=df['Open']-9.44

In [14]:
df.head()

,Unnamed: 0,Date,Open,High,Low,Close,diffHigh,difflow,diffClose,Average,Target_price1,Target_price2
0,251,2019-02-01,2476.96,2519.49,2467.47,2510.03,42.53,9.49,33.07,28.363333,2486.40,2467.52
1,250,2019-03-01,2491.92,2493.14,2443.96,2447.89,1.22,47.96,-44.03,1.716667,2501.36,2482.48
2,249,2019-04-01,2474.33,2538.07,2474.33,2531.94,63.74,0.00,57.61,40.450000,2483.77,2464.89
3,248,2019-07-01,2535.61,2566.16,2524.56,2549.69,30.55,11.05,14.08,18.560000,2545.05,2526.17
4,247,2019-08-01,2568.11,2579.82,2547.56,2574.41,11.71,20.55,6.30,12.853333,2577.55,2558.67

In [15]:
df['gain_lost1']=np.select([df['Target_price1']<df['High'],df['Target_price1']>df['High']], ['Gain','Lost'])

In [16]:
df['gain_lost1'].value_counts()

Gain    477
Lost    280
Name: gain_lost1, dtype: int64

In [17]:
df['gain_lost2']=np.select([df['Target_price2']<df['Low'],df['Target_price2']>df['Low']], ['Lost','Gain'])

In [18]:
df['gain_lost2'].value_counts()
#Accuracy 56%

Gain    429
Lost    328
Name: gain_lost2, dtype: int64

Accuracy= 61% 
BASED ON THIS WORK THE ACCURACY OF OUR ALGORITHM IS 61% WHICH IS CALCULATED BY DIVIDING THE NUMBER OF Gain BY THE TOTAL NUMBER OF OBSERVATIONS 503 THEN MULTIPLY BY 100

Validation using S&P 2022 Data

In [19]:
df2=pd.read_csv('SP_2022.csv')

In [20]:
df2.dtypes

Date     object
Open     object
High     object
Low      object
Close    object
dtype: object

In [21]:
df2["Open"] = [float(str(i).replace(",", "")) for i in df2["Open"]]

In [22]:
df2["High"] = [float(str(i).replace(",", "")) for i in df2["High"]]

In [23]:
df2["Low"] = [float(str(i).replace(",", "")) for i in df2["Low"]]

In [24]:
df2["Close"] = [float(str(i).replace(",", "")) for i in df2["Close"]]

In [25]:
df2['Date'] = df2["Date"].astype('datetime64[ns]')

In [26]:
df2['Target_price1']=df2['Open']+9.44

In [27]:
df2['Gain_lost1'] = np.select([df2['Target_price1']<df2['High'],df2['Target_price1']>df2['High']], ['Gain','Lost'])
df2.head()

        Date     Open     High      Low    Close  Target_price1 Gain_lost1
0 2022-12-30  3828.85  3839.85  3800.34  3839.50        3838.29       Gain
1 2022-12-29  3805.45  3858.19  3805.45  3849.28        3814.89       Gain
2 2022-12-28  3829.56  3848.32  3780.78  3783.22        3839.00       Gain
3 2022-12-27  3843.34  3846.65  3813.22  3829.25        3852.78       Lost
4 2022-12-23  3813.11  3845.80  3797.01  3844.82        3822.55       Gain

In [28]:
df2["Gain_lost1"].value_counts()
#81% Accuracy

Gain    204
Lost     47
Name: Gain_lost1, dtype: int64